Revert "libbinder: avoid global mutex every binder call"
This reverts commit bdbd4660a49a3ddaaa3da955adcc9fafa565b31e.

Reason for revert: build fails with following error: 

error: VNDK library: libbinder's ABI has INCOMPATIBLE CHANGES Please check compatibility report at: out/soong/.intermediates/frameworks/native/libs/binder/libbinder/android_vendor.30_arm64_armv8-a_kryo_shared/libbinder.so.abidiff
******************************************************
error: Please update ABI references with: $ANDROID_BUILD_TOP/development/vndk/tools/header-checker/utils/create_reference_dumps.py  -l libbinder

Change-Id: Id830eba24b9f11459c8dbffa7e3ccfa8e1f02188